<?php

namespace Database\Seeders;

use App\Models\Publisher;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Publisher::insert([
            'name' => 'Vachanavayal',
            'address' => 'Bible House, 206 M.G. Road, Bangalore - 560 001',
            'logo' => 'https://bibliya.in/storage/bibliya_logo.png',
        ]);
        DB::table('books')->insert([
            [
                'order_no' => 1,
                'max_chapters' => 50,
                'from' => 'old_testament',
                'eng_name' => 'Genesis',
                'mal_name' => 'ഉല്പത്തി',
                'type' => 'bible',
                'is_active' => false,
            ],
            [
                'order_no' => 2,
                'from' => 'old_testament',
                'max_chapters' => 40,
                'eng_name' => 'Exodus',
                'mal_name' => 'പുറപ്പാട്‌',
                'type' => 'bible',
                'is_active' => false,
            ],
            [
                'from' => 'old_testament',
                'order_no' => 3,
                'max_chapters' => 28,
                'eng_name' => 'Leviticus',
                'mal_name' => 'ലേവ്യർ',
                'type' => 'bible',
                'is_active' => false,
            ],
            [
                'order_no' => 4,
                'max_chapters' => 36,
                'eng_name' => 'Numbers',
                'mal_name' => 'സംഖ്യാ',
                'from' => 'old_testament',
                'type' => 'bible',
                'is_active' => false,
            ],
            [
                'order_no' => 5,
                'from' => 'old_testament',
                'max_chapters' => 34,
                'eng_name' => 'Deuteronomy',
                'mal_name' => 'നിയമാവർത്തനം',
                'type' => 'bible',
                'is_active' => false,
            ],
            [
                'order_no' => 6,
                'max_chapters' => 24,
                'from' => 'old_testament',
                'eng_name' => 'Joshua',
                'mal_name' => 'ജോഷ്വാ',
                'type' => 'bible',
                'is_active' => false,
            ],
            [
                'order_no' => 7,
                'max_chapters' => 21,
                'eng_name' => 'Judges',
                'from' => 'old_testament',
                'mal_name' => 'ന്യായാധിപന്മാർ',
                'type' => 'bible',
                'is_active' => false,
            ],
            [
                'order_no' => 8,
                'max_chapters' => 4,
                'eng_name' => 'Ruth',
                'mal_name' => 'റൂത്ത്',
                'from' => 'old_testament',
                'type' => 'bible',
                'is_active' => false,
            ],
            [
                'order_no' => 9,
                'max_chapters' => 31,
                'eng_name' => '1 Samuel',
                'mal_name' => '1 ശമൂവേൽ',
                'type' => 'bible',
                'from' => 'old_testament',
                'is_active' => false,
            ],
            [
                'order_no' => 10,
                'max_chapters' => 24,
                'eng_name' => '2 Samuel',
                'mal_name' => '2 ശമൂവേൽ',
                'type' => 'bible',
                'from' => 'old_testament',
                'is_active' => false,
            ],
            [
                'order_no' => 11,
                'max_chapters' => 22,
                'eng_name' => '1 Kings',
                'mal_name' => '1 രാജാക്കൻമാർ',
                'type' => 'bible',
                'from' => 'old_testament',
                'is_active' => false,
            ],
            [
                'order_no' => 12,
                'max_chapters' => 25,
                'from' => 'old_testament',
                'eng_name' => '2 Kings',
                'mal_name' => '2 രാജാക്കൻമാർ',
                'type' => 'bible',
                'is_active' => false,
            ],
            [
                'order_no' => 13,
                'max_chapters' => 29,
                'from' => 'old_testament',
                'eng_name' => '1 Chronicles',
                'mal_name' => '1 ദിനവൃത്താന്തം',
                'type' => 'bible',
                'is_active' => false,
            ],
            [
                'order_no' => 14,
                'max_chapters' => 36,
                'eng_name' => '2 Chronicles',
                'mal_name' => '2 ദിനവൃത്താന്തം',
                'type' => 'bible',
                'from' => 'old_testament',
                'is_active' => false,
            ],
            [
                'order_no' => 15,
                'max_chapters' => 10,
                'eng_name' => 'Ezra',
                'mal_name' => 'എസ്രാ',
                'type' => 'bible',
                'from' => 'old_testament',
                'is_active' => false,
            ],
            [
                'order_no' => 16,
                'max_chapters' => 13,
                'eng_name' => 'Nehemiah',
                'mal_name' => 'നെഹെമ്യാവു',
                'type' => 'bible',
                'from' => 'old_testament',
                'is_active' => false,
            ],
            [
                'order_no' => 17,
                'max_chapters' => 10,
                'eng_name' => 'Esther',
                'mal_name' => 'എസ്തേർ',
                'type' => 'bible',
                'from' => 'old_testament',
                'is_active' => false,
            ],
            [
                'order_no' => 18,
                'max_chapters' => 42,
                'eng_name' => 'Job',
                'mal_name' => 'യോബ്',
                'type' => 'bible',
                'from' => 'old_testament',
                'is_active' => false,
            ],
            [
                'order_no' => 19,
                'max_chapters' => 150,
                'eng_name' => 'Psalms',
                'mal_name' => 'സങ്കീർത്തനങ്ങൾ',
                'type' => 'bible',
                'from' => 'old_testament',
                'is_active' => false,
            ],
            [
                'order_no' => 20,
                'max_chapters' => 31,
                'eng_name' => 'Proverbs',
                'mal_name' => 'സദൃശ്യവാക്യങ്ങൾ',
                'type' => 'bible',
                'from' => 'old_testament',
                'is_active' => false,
            ],
            [
                'order_no' => 21,
                'max_chapters' => 12,
                'eng_name' => 'Ecclesiastes',
                'mal_name' => 'സഭാപ്രസംഗി',
                'type' => 'bible',
                'is_active' => false,
                'from' => 'old_testament',
            ],
            [
                'order_no' => 22,
                'max_chapters' => 8,
                'eng_name' => 'Song of Songs',
                'mal_name' => 'ഉത്തമഗീതം',
                'type' => 'bible',
                'is_active' => false,
                'from' => 'old_testament',
            ],
            [
                'order_no' => 23,
                'max_chapters' => 66,
                'eng_name' => 'Isaiah',
                'mal_name' => 'യേശയ്യാവ്',
                'type' => 'bible',
                'is_active' => false,
                'from' => 'old_testament',
            ],
            [
                'order_no' => 24,
                'max_chapters' => 52,
                'eng_name' => 'Jeremiah',
                'mal_name' => 'യിരമ്യാവു',
                'type' => 'bible',
                'is_active' => false,
                'from' => 'old_testament',
            ],
            [
                'order_no' => 25,
                'max_chapters' => 5,
                'eng_name' => 'Lamentations',
                'mal_name' => 'വിലാപങ്ങൾ',
                'type' => 'bible',
                'is_active' => false,
                'from' => 'old_testament',
            ],
            [
                'order_no' => 26,
                'max_chapters' => 48,
                'eng_name' => 'Ezekiel',
                'mal_name' => 'യെഹെസ്‌കേൽ',
                'type' => 'bible',
                'is_active' => false,
                'from' => 'old_testament',
            ],
            [
                'order_no' => 27,
                'max_chapters' => 12,
                'eng_name' => 'Daniel',
                'mal_name' => 'ദാനിയേൽ',
                'type' => 'bible',
                'is_active' => false,
                'from' => 'old_testament',
            ],
            [
                'order_no' => 28,
                'max_chapters' => 14,
                'eng_name' => 'Hosea',
                'mal_name' => 'ഹോസേയ',
                'type' => 'bible',
                'is_active' => false,
                'from' => 'old_testament',
            ],
            [
                'order_no' => 29,
                'max_chapters' => 3,
                'eng_name' => 'Joel',
                'mal_name' => 'യോവേൽ',
                'type' => 'bible',
                'is_active' => false,
                'from' => 'old_testament',
            ],
            [
                'order_no' => 30,
                'max_chapters' => 9,
                'eng_name' => 'Amos',
                'mal_name' => 'ആമോസ്',
                'type' => 'bible',
                'is_active' => false,
                'from' => 'old_testament',

            ],
        ]);
    }
}
